# Generated by Django 4.2.3 on 2023-07-31 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, 'BASIC'), (1, 'INTERMEDIATE'), (2, 'ADVANCED')])),
                ('type', models.PositiveIntegerField(blank=True, choices=[(0, '上衣/二頭彎舉'), (1, '下著/伏地挺身'), (2, '鞋子/深蹲')])),
                ('color', models.PositiveIntegerField(blank=True, choices=[(0, 'STYLE_A'), (1, 'STYLE_B'), (2, 'STYLE_C')])),
                ('work_max', models.IntegerField(blank=True, null=True)),
                ('exp', models.FloatField(blank=True, default=0)),
                ('lucky', models.FloatField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gear',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gear')),
            ],
            options={
                'db_table': 'exercise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, '初級小物'), (1, '中級小物'), (2, '高級小物')])),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thing',
                'managed': True,
                'unique_together': {('user', 'level')},
            },
        ),
    ]
