# Generated by Django 4.2.3 on 2023-07-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='gear',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
