# Generated by Django 4.2.3 on 2023-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='loaded',
            field=models.BooleanField(default=True),
        ),
    ]
