# Generated by Django 4.2.3 on 2023-08-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_video_url_gear_img_url'),
        ('api', '0019_alter_gear_user'),
    ]

    operations = [
    ]
