# Generated by Django 4.2.3 on 2023-08-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
    ]
