# Generated by Django 4.2.2 on 2023-06-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eq',
            fields=[
                ('nid', models.IntegerField(db_column='Nid', primary_key=True, serialize=False)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('work_max', models.IntegerField(blank=True, null=True)),
                ('exp', models.FloatField(blank=True, null=True)),
                ('lucky', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'eq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(db_column='Uid', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('wallet_addr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app01.users')),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('type', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app01.users')),
            ],
            options={
                'db_table': 'things',
                'managed': False,
            },
        ),
    ]
